development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:1eceeaed1af7764dcad858e28a6d5141@porgy.redistogo.com:11994/
  channel_prefix: PackedRight2_production
