meta_product_name: "PackedRight"
meta_title: "PackedRight - Let us take care of your package"
meta_description: "Easy and fast same-day-delivery of all your parcels, delivered by our trusted and experienced drivers."
meta_image: "cover.png"
twitter_account: "@product_twitter_account"
